### ISSUE TITLE
Уменьшение размера репозитория

### ISSUE THREAD

**Issue by denisshevchenko** [denisshevchenko/ohaskell.guide#24]
Удаление полной истории бинарных файлов книги, для сохранения малого размера репозитория.

**Comment by denisshevchenko** [comment]
Спасибо @cblp за шаблон: https://github.com/cblp/cv/blob/master/GitHubPages.hs

**Comment by cblp** [comment]
Желательно и master будет очистить от epub/pdf.

**Comment by cblp** [comment]
И не забыть на главной поправить ссылки, чтобы они вели не на репозиторий с кодом, а на локальные файлы на сайте.

**Comment by denisshevchenko** [comment]
Конечно.

**Comment by denisshevchenko** [comment]
Готово. Скрипт изменил, теперь история в ветке `gh-pages` не накапливается, там сохраняется лишь один последний коммит с реальными сгенерированными файлами, и при каждом деплое этот коммит форс-пушится. А всю уже имеющуюся историю в `gh-pages` я хард-ресетнул.
