### ISSUE TITLE
Проблемы в epub-версии.

### ISSUE THREAD

**Issue by fomkin** [denisshevchenko/ohaskell.guide#29]
Денис, здравствуйте! Я заметил ряд проблем в epub-версии и хочу про них рассказать. Читал в стандпртной айфоновской читалке.

1. На небольшом экране (iPhone 6) при портретной ориентации примеры кода практически всегда переносится. То есть книга становится практически нечитаемой.
2. В некоторых местах я заметил переносы (со знаком переноса) в коде.
3. При этом текст идет без переносов, выровненный по двум краям.

**Comment by denisshevchenko** [comment]
Приветствую, Алексей!

Благодарю за отклик. Отвечаю:

>     На небольшом экране (iPhone 6) при портретной ориентации примеры кода практически всегда переносится. То есть книга становится практически нечитаемой.

Да, это так. Но ведь у многих на руках ещё iPhone 5, однако подстраиваться под его 4-дюймовый экран в портретной ориентации я точно не стану, в противном случае строчки кода должны стать уж слишком короткими. Однако в **горизонтальной** ориентации даже на iPhone 5 код прекрасно читается, длины экрана вполне хватает.

Если же кто принципиально желает читать книгу на смартфоне и именно в портретной ориентации - я могу дать только один совет: читайте веб-вариант. Он адаптивный под малые экраны, и все примеры кода в нём имеют горизонтальную прокрутку, что исключает перенос и "скомкивание" кода.

>     В некоторых местах я заметил переносы (со знаком переноса) в коде.
Да?? Странно, не замечал. Нужно будет проверить тщательнее. Спасибо.

>     При этом текст идет без переносов, выровненный по двум краям.

Это сделано сознательно. В книгах на русском языке в EPUB-формате (я смотрел на примере классики) переносы есть, но текст имеет рваный край справа (по крайней мере, на 4-дюймовом экране в портретной ориентации). Я категорически не приемлю рваные края в тексте любой книги. Так что уж лучше пусть будет строгое выравнивание, но без переносов.

**Comment by fomkin** [comment]
> Это сделано сознательно. В книгах на русском языке в EPUB-формате (я смотрел на примере классики) переносы есть, но текст имеет рваный край справа (по крайней мере, на 4-дюймовом экране в портретной ориентации). Я категорически не приемлю рваные края в тексте любой книги. Так что уж лучше пусть будет строгое выравнивание, но без переносов.

А разве нельзя использовать и то и другое одновременно? Я правильно понимаю что в ePub запакована та же веб-версия? Вот пример где одновременно расставлены мягкие переносы и применено выравнивание по краям https://jsfiddle.net/t9c7td04/

**Comment by denisshevchenko** [comment]
И что, ты предлагаешь мне вставлять в каждое слово `&shy;`?? Переносы слов в PDF делает LaTeX, с помощью специальных шаблонов переносов для кириллических языков (проверял на украинском, работает). LaTeX делает это автоматически. Если я найду автоматический способ расстановки переносов для EPUB - буду очень рад. Но пока не нашёл..

**Comment by fomkin** [comment]
> И что, ты предлагаешь мне вставлять в каждое слово `&shy;`?? Надеюсь, это шутка... ;-)

Я предполагал, что Ипаб тоже ЛаТеХом генерируется. Вообще что бы расставить эти самые `&shy;` нужно реализовать алгоритм Лянга-Кнута (он не сложный) и взять набор правил для русского языка из того же ЛаТеХовского пакета. Если ты скажешь куда это вставлять, то могу заняться.

**Comment by denisshevchenko** [comment]
> Если ты скажешь куда это вставлять, то могу заняться.

Скажу. Перед формированием PDF/EPUB создаётся временный Markdown, состоящий из всех глав, склееных по порядку. 

https://github.com/denisshevchenko/ohaskell.guide/blob/master/src/SingleMarkdown.hs#L26

Вот в этот временный Markdown ПЕРЕД тем, как его записывать в файл, и нужно вставлять все эти `&shy;`.

**Comment by fomkin** [comment]
> Вот в этот временный Markdown ПЕРЕД тем, как его записывать в файл, и нужно вставлять все эти &shy;. Код, реализующий эту вставку, лучше вынести в отдельный модуль, разумеется.

Окей. План такой:

1. Пандоком (его ведь можно подключать как библиотеку?) разбираю получившийся маркдаун на AST. Почему это нужно: хочется расставлять переносы только в тексте и не расставлять в примерах.
2. Подключаю https://hackage.haskell.org/package/hyphenation
3. Расставляю переносы только в тексте
4. Собираю маркдаун обратно в текст

Создам новую задачку под это дело. Заниматься я этим буду недели две как минимум, потому что опыта с хаскелем у меня нет.
